### ISSUE TITLE
Facets knowledge panels is throwing a lot of logs because of an error that should not raise

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/facets-knowledge-panels#103]
### What

A lot of this error is reported in logs:

```
16:23:48.508
ERROR:root:exception in _wikidata_kp
16:23:48.508
Traceback (most recent call last):
16:23:48.508
  File "/code/./app/exception_wrapper.py", line 18, in wrapper
16:23:48.508
    return await func(*args, **kwargs)
16:23:48.508
  File "/code/./app/knowledge_panels.py", line 215, in _wikidata_kp
16:23:48.508
    return await wikidata_helper(query=query, value=value)
16:23:48.508
  File "/code/./app/off.py", line 173, in wikidata_helper
16:23:48.508
    entity_id = in_lang(tag["wikidata"], lang)
16:23:48.508
KeyError: 'wikidata'
```

![image](https://user-images.githubusercontent.com/144788/225950852-35a976b1-91f4-4ccd-be26-7a7a7e6cd862.png)

This lead to flooding the logs, see https://github.com/openfoodfacts/openfoodfacts-infrastructure/issues/195

**Comment by alexgarel** [comment]
In facts the issue is correctly caught by [`no_exception` function](https://github.com/openfoodfacts/facets-knowledge-panels/blob/v1.1.2/app/exception_wrapper.py#L5) but it also logs (I imagine it's me who asked for logging !).

I will add a `log_errors` parameter for now, but it's not very satisfying !
