### ISSUE TITLE
Server Error with en:lemonades category

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/facets-knowledge-panels#85]
### What
https://facets-kp.openfoodfacts.net/knowledge_panel?lang_code=fr&facet_tag=category&value_tag=en:lemonades
returns a server error.

### Expected behavior
Should not lead to a server error but only displays panels that are computable

### logs

```
facets-api_1  | ERROR:root:While adding wikidata for primary facet
facets-api_1  | Traceback (most recent call last):
facets-api_1  |   File "/code/./app/knowledge_panels.py", line 217, in wikidata_kp
facets-api_1  |     entity = await self._wikidata_kp(facet=facet, value=value)
facets-api_1  |   File "/code/./app/knowledge_panels.py", line 205, in _wikidata_kp
facets-api_1  |     return await wikidata_helper(query=query, value=value)
facets-api_1  |   File "/code/./app/off.py", line 177, in wikidata_helper
facets-api_1  |     entity_id = in_lang(tag["wikidata"], lang)
facets-api_1  | KeyError: 'wikidata'
facets-api_1  | INFO:     10.1.0.101:34526 - "GET /knowledge_panel?lang_code=fr&facet_tag=category&value_tag=en:lemonades HTTP/1.0" 500 Internal Server Error
facets-api_1  | ERROR:    Exception in ASGI application
facets-api_1  | Traceback (most recent call last):
facets-api_1  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
facets-api_1  |     result = await app(self.scope, self.receive, self.send)
facets-api_1  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
facets-api_1  |     return await self.app(scope, receive, send)
facets-api_1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 269, in __call__
facets-api_1  |     await super().__call__(scope, receive, send)
facets-api_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 124, in __call__
facets-api_1  |     await self.middleware_stack(scope, receive, send)
facets-api_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
facets-api_1  |     raise exc
facets-api_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
facets-api_1  |     await self.app(scope, receive, _send)
facets-api_1  |   File "/usr/local/lib/python3.9/site-packages/prometheus_fastapi_instrumentator/middleware.py", line 103, in __call__
facets-api_1  |     raise exc
facets-api_1  |   File "/usr/local/lib/python3.9/site-packages/prometheus_fastapi_instrumentator/middleware.py", line 101, in __call__
facets-api_1  |     await self.app(scope, receive, send_wrapper)
facets-api_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 93, in __call__
facets-api_1  |     raise exc
facets-api_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
facets-api_1  |     await self.app(scope, receive, sender)
facets-api_1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
facets-api_1  |     raise e
facets-api_1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
facets-api_1  |     await self.app(scope, receive, send)
facets-api_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 670, in __call__
facets-api_1  |     await route.handle(scope, receive, send)
facets-api_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 266, in handle
facets-api_1  |     await self.app(scope, receive, send)
facets-api_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 65, in app
facets-api_1  |     response = await func(request)
facets-api_1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 227, in app
facets-api_1  |     raw_response = await run_endpoint_function(
facets-api_1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
facets-api_1  |     return await dependant.call(**values)
facets-api_1  |   File "/code/./app/main.py", line 104, in knowledge_panel
facets-api_1  |     soon_panels.append(task_group.soonify(obj_kp.wikidata_kp)())
facets-api_1  |   File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
facets-api_1  |     raise exceptions[0]
facets-api_1  |   File "/usr/local/lib/python3.9/site-packages/asyncer/_main.py", line 145, in value_wrapper
facets-api_1  |     value = await partial_f()
facets-api_1  |   File "/code/./app/knowledge_panels.py", line 124, in data_quality_kp
facets-api_1  |     data = await data_quality(url=url, path=path)
facets-api_1  |   File "/code/./app/off.py", line 52, in data_quality
facets-api_1  |     tags = data["tags"]
facets-api_1  | KeyError: 'tags'
facets-api_1  | ERROR:uvicorn.error:Exception in ASGI application
facets-api_1  | Traceback (most recent call last):
facets-api_1  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
facets-api_1  |     result = await app(self.scope, self.receive, self.send)
facets-api_1  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
facets-api_1  |     return await self.app(scope, receive, send)
facets-api_1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 269, in __call__
facets-api_1  |     await super().__call__(scope, receive, send)
facets-api_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 124, in __call__
facets-api_1  |     await self.middleware_stack(scope, receive, send)
facets-api_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
facets-api_1  |     raise exc
facets-api_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
facets-api_1  |     await self.app(scope, receive, _send)
facets-api_1  |   File "/usr/local/lib/python3.9/site-packages/prometheus_fastapi_instrumentator/middleware.py", line 103, in __call__
facets-api_1  |     raise exc
facets-api_1  |   File "/usr/local/lib/python3.9/site-packages/prometheus_fastapi_instrumentator/middleware.py", line 101, in __call__
facets-api_1  |     await self.app(scope, receive, send_wrapper)
facets-api_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 93, in __call__
facets-api_1  |     raise exc
facets-api_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
facets-api_1  |     await self.app(scope, receive, sender)
facets-api_1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
facets-api_1  |     raise e
facets-api_1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
facets-api_1  |     await self.app(scope, receive, send)
facets-api_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 670, in __call__
facets-api_1  |     await route.handle(scope, receive, send)
facets-api_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 266, in handle
facets-api_1  |     await self.app(scope, receive, send)
facets-api_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 65, in app
facets-api_1  |     response = await func(request)
facets-api_1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 227, in app
facets-api_1  |     raw_response = await run_endpoint_function(
facets-api_1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
facets-api_1  |     return await dependant.call(**values)
facets-api_1  |   File "/code/./app/main.py", line 104, in knowledge_panel
facets-api_1  |     soon_panels.append(task_group.soonify(obj_kp.wikidata_kp)())
facets-api_1  |   File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
facets-api_1  |     raise exceptions[0]
facets-api_1  |   File "/usr/local/lib/python3.9/site-packages/asyncer/_main.py", line 145, in value_wrapper
facets-api_1  |     value = await partial_f()
facets-api_1  |   File "/code/./app/knowledge_panels.py", line 124, in data_quality_kp
facets-api_1  |     data = await data_quality(url=url, path=path)
facets-api_1  |   File "/code/./app/off.py", line 52, in data_quality
facets-api_1  |     tags = data["tags"]
facets-api_1  | KeyError: 'tags'
```

**Comment by alexgarel** [comment]
It's due to this bug : https://github.com/openfoodfacts/openfoodfacts-server/issues/7979

But maybe we should avoid a server error ?

**Comment by alexgarel** [comment]
Kudos for fixing this @sumit-158
